### ISSUE TITLE
Can't compile autograph in Xcode 10.2

### ISSUE THREAD

**Issue by PatoSalazarNascent** [remind101/AutoGraph#101]
My project is using  pod that uses Autograph and since I updated to the latest Xcode 10.2 I can't compile it.

This is the error I am getting

<img width="276" alt="Screen Shot 2019-05-01 at 3 33 13 PM" src="https://user-images.githubusercontent.com/13645886/57082792-75aadd80-6cc5-11e9-9149-cefb22061e42.png">

Any ideas how can I go around this?? Have you heard or someone else having this issue...??

Thanks

**Comment by rex-remind101** [comment]
Could you please provide the name of the pod that uses AutoGraph so I can reproduce the case?

**Comment by PatoSalazarNascent** [comment]
@remind101-github  I need to talk with the people who created the sdk we are using to see if they can share it with you... I'll follow up on Monday

**Comment by rex-remind101** [comment]
@PatoSalazarNascent I have isolated the issue. It seems that in swift 5's compiler there's a bug with cross-module retroactive protocol conformance. I know the swift team has been debating the workability of this for a while, must have overlooked a certain edge case. I added a work around that should fix the problem and published a new release `0.8.0`. Please let the authors of the sdk you're using know that the new release should fix the issue, and please let us know if there are any remaining issues. Also, I'll report the bug to the swift team when i find time. Thanks for the bug report!

**Comment by PatoSalazarNascent** [comment]
@rex-remind101 I will, thanks so much for the quick response!...I'll let the sdk team know

**Comment by PatoSalazarNascent** [comment]
@rex-remind101 so your fix worked. The only thing I am having issues now is that Alamofire (that I think you guys are using for your pod) has a `Result<arg>` class that is clashing with `Result<arg1, arg2>` from the core language. But I think this is beyond your fix. 

Thanks so much!

**Comment by rex-remind101** [comment]
@PatoSalazarNascent `Swift.Result` will give you the native `Result` type. `Swift` is the module namespace of the standard library, that should help :)

**Comment by PatoSalazarNascent** [comment]
I saw that @rex-remind101 ... you replaced your old Result class by the new native one. We are updating our code now. Thanks for all your help
