### ISSUE TITLE
AlamoFire dependency causes incompatibility error when building library in latest xcode

### ISSUE THREAD

**Issue by PatoSalazarNascent** [remind101/AutoGraph#109]
You are using AlamoFire `4.8.2` which has not active module resiliency and causes the following error during compilation `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler`

Please check this issue in the AlamoFire GitHub

[https://github.com/Alamofire/Alamofire/issues/2990](https://github.com/Alamofire/Alamofire/issues/2990)

This is solved for AlamoFire V5. Is there any chance you can update your AlamoFire version??

**Comment by rex-remind101** [comment]
Thanks for opening this, will fix asap.

**Comment by PatoSalazarNascent** [comment]
@rex-remind101 Hey no problem, just make sure of what I am saying actually make sense... 📦

**Comment by rex-remind101** [comment]
From what I can tell, the issue you're asking about is you wish to compile a resilient module that does not have resiliency enabled, but there's a few issues with that.
* Alamofire won't support module stability on latest versions, yet AutoGraph always wants to support the latest production ready version of Alamofire ideally. That implies that Alamofire will only guarantee resilience on libraries that are deemed older versions.
```
However, it may make sense to enable it on v4, especially once we release v5. I'll keep this issue open to ensure we make that release when we release 5.0.0.
```
* We can follow a similar strategy but we're still on 0.x releases, so we can't have resiliency guarantees anyway. Once we move to major releases (which we can probably start doing soon) we can pursue the same strategy.

I'm also unsure of why you might want resilience? And how this is guarantee is manifesting in your application? Are you using Carthage, Cocoapods, or SPM? Maybe you can clarify?

Also, where do you see that it is solved in Alamofire v5?

**Comment by PatoSalazarNascent** [comment]
I am using Cocoapods....
And we are using a pod that happens to be using Autograph and we starting getting this error when we tried to update that pod to its latest version.  So we starting tracking down dependencies and all we can see is AlamoFire having this issue.

```Alamofire will not be enabling module resiliency for actively developed versions due to the rather extreme restrictions it places on the library's evolution. However, it may make sense to enable it on v4, especially once we release v5. I'll keep this issue open to ensure we make that release when we release 5.0.0. ```

But people keeps complaining this has not been resolved for version older than five. Which make us think that upgrading to AlamoFire 5 might be what is need to be done.

If this does not make sense, I can close the issue and look for an alternative in our end...

Thanks!

**Comment by rex-remind101** [comment]
What's the pod that happens to use AutoGraph? I can take a look and see what might be the cause from that end. We use Cocoapods and SPM here and both work fine with AutoGraph (by itself) on Xcode 11.2 / Swift 5.1.2.

**Comment by PatoSalazarNascent** [comment]
@rex-remind101  It is a private pod for Beacon detection. Let me investigate a bit more, maybe I was to hasty in pinpointing this to Autograph... I'll keep you posted
