### ISSUE TITLE
handle null return from the server. 

### ISSUE THREAD

**Issue by princefr** [remind101/AutoGraph#122]
Hi , i've a call that return null when a data is not found in the database.
like when a user is not found.

`{
    "data": {
        "user": null
    }
}`

it result in a [NSJSONSerialization dataWithJSONObject:options:error:]: Invalid top-level type in JSON write in swift when I launch the app.

the error is triggered by `public func didFinishRequest(response: HTTPURLResponse?, json: JSONValue) throws { }`
how can I handle null data with autograph

**Comment by rex-remind101** [comment]
I think i'll need more code and context to understand your problem better. But fwiw, `didFinishRequest(response:json:)` is called to the user of AutoGraph when the request finishes. Whatever happens from within that function is up to you.
